name: 'Archive and upload Build Artifacts'
description: 'Archive build artifacts and upload them so that they can be used by subsequent workflow steps.'
author: Rainer Schlönvoigt

branding:
  icon: 'arrow-up'
  color: 'green'

inputs: 
  name:
    description: 'Artifact name'
    default: 'artifact'
  directory:
    description: 'The base directory '
    default: '.'
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload. These must be relative to the `directory` input parameter.'
    required: true
  retention-days:
    description: >
      Duration after which artifact will expire in days. 0 means using default retention.
      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.

runs:
  using: composite
  steps:
    - id: generate-name
      run: |
        # It is possible to call this action multiple times.
        # Ideally we want to store the files from all the calls, not overwrite them.
        # Therefore, the archive can't have a fixed name.
        RANDOM_ELEMENT=$(dd bs=512 if=/dev/urandom count=1 2>/dev/null | env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        ZIP_NAME="${RANDOM_ELEMENT}.rTmpArchive.zip"

        echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
      shell: bash
    - name: Archive Build Artifacts
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: ${{ steps.generate-name.outputs.zip_name }}
        directory: ${{ inputs.directory }}
        path: ${{ inputs.path }}
    - name: Upload Archive
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{ inputs.name }}
        retention-days: ${{ inputs.retention-days }}
        path: ${{ inputs.directory }}/${{ steps.generate-name.outputs.zip_name }}
        if-no-files-found: error
    - name: Clean up
      if: always()
      run: rm ${{ inputs.directory }}/${{ steps.generate-name.outputs.zip_name }}
      shell: bash
