name: 'Archive and upload Build Artifacts'
description: 'Archive build artifacts and upload them so that they can be used by subsequent workflow steps.'
author: Rainer Schlönvoigt
inputs: 
  name:
    description: 'Artifact name'
    default: 'artifact'
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
  if-no-files-found:
    description: >
      The desired behavior if no files are found using the provided path.
      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    default: 'warn'
  retention-days:
    description: >
      Duration after which artifact will expire in days. 0 means using default retention.
      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.

runs:
  using: composite
  steps:
    - name: Archive Build Artifacts
      id: archive-artifacts
      run: |
        #TODO: Check if files exist

        # It is possible to call this action multiple times.
        # Ideally we want to store the files from all the calls, not overwrite them.
        # Therefore, the archive can't have a fixed name.
        RANDOM_ELEMENT=$(cat /dev/urandom | env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        #ZIP_NAME="${RANDOM_ELEMENT}.rTmpArchive.zip"

        # echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

        # ACTION_INPUT_PATHS="${{ inputs.path }}"
        # echo $ACTION_INPUT_PATHS | while IFS= read -r ACTION_INPUT_PATH
        # do
        #   zip -r "$ZIP_NAME" $ACTION_INPUT_PATH
        # done
      shell: bash
    - name: Upload Archive
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        retention-days: ${{ inputs.retention-days }}
        path: ${{ steps.archive-artifacts.outputs.zip_name }}
        if-no-files-found: error