name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  single-file-upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Upload
      uses: ./
      with:
        name: "Single-File"
        path: DirA/SubDirA/FileAA.md
        retention-days: 1
    - name: Download Archive
      uses: actions/download-artifact@v3
      with:
        name: "Single-File"
        path: check
    - name: Check Archive Exists
      run: |
        count=$(ls -1 *.rTmpArchive.zip 2>/dev/null | wc -l)
        if [ $count != 1 ]
          echo "Missing archive file!"
          exit 1
        fi
      working-directory: check
    - name: Check Archive contents
      run: |
        unzip *.rTmpArchive.zip -d ./tmp

        if [ ! -f 'tmp/FileAA.md' ]; then
          echo "Missing archive contents!"
          exit 1
        fi
      working-directory: check

     
