name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  single-file-upload:
    name: Single File Upload Test
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Upload
      uses: ./
      with:
        name: single-file-${{ matrix.runs-on }}
        path: __testFiles__/DirA/SubDirA/FileAA.md
        retention-days: 1
    - name: Upload Comparison
      uses: actions/upload-artifact@v3
      with:
        name: comparison-single-${{ matrix.runs-on }}
        retention-days: 1
        path: __testFiles__/DirA/SubDirA/FileAA.md
        if-no-files-found: error
    - name: Download Archive
      uses: actions/download-artifact@v3
      with:
        name: single-file-${{ matrix.runs-on }}
        path: check
    - name: Check Archive Exists
      run: |
        count=$(ls -1 *.rTmpArchive.zip 2>/dev/null | wc -l)
        if [ $count != 1 ]; then
          echo "Missing archive file!"
          exit 1
        fi
      working-directory: check
    - name: Check Archive contents
      run: |
        unzip *.rTmpArchive.zip -d ./tmp

        if [ ! -f 'tmp/FileAA.md' ]; then
          echo "Missing archive contents!"
          exit 1
        fi
      working-directory: check

  multi-file-upload:
    name: Multiple Files Upload Test
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Upload
      uses: ./
      with:
        name: multiple-files-${{ matrix.runs-on }}
        path: __testFiles__/**
        retention-days: 1
    - name: Upload Comparison
      uses: actions/upload-artifact@v3
      with:
        name: comparison-multiple-${{ matrix.runs-on }}
        retention-days: 1
        path: __testFiles__/**
        if-no-files-found: error
    - name: Download Archive
      uses: actions/download-artifact@v3
      with:
        name: multiple-files-${{ matrix.runs-on }}
        path: check
    - name: Check Archive Exists
      run: |
        count=$(ls -1 *.rTmpArchive.zip 2>/dev/null | wc -l)
        if [ $count != 1 ]; then
          echo "Missing archive file!"
          exit 1
        fi
      working-directory: check
    - name: Check Archive contents
      run: |
        unzip *.rTmpArchive.zip -d check/tmp

        diff __testFiles__ check/tmp