name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
        config:
          - name: Single
            path: __testFiles__/DirA/SubDirA/FileAA.md
            expanded_paths: __testFiles__/DirA/SubDirA/FileAA.md
          - name: Multiple
            path: __testFiles__/**
            expanded_paths: |
              __testFiles__/DirA/SubDirA/FileAA.md
              __testFiles__/DirA/SubDirB/FileAB.md
              __testFiles__/DirA/FileA.md
              __testFiles__/DirB/FileB.md
              __testFiles__/Foo
          - name: Multiple2
            path: |
              __testFiles__/DirA
              __testFiles__/DirB/**
            expanded_paths: |
              __testFiles__/DirA/SubDirA/FileAA.md
              __testFiles__/DirA/SubDirB/FileAB.md
              __testFiles__/DirA/FileA.md

      fail-fast: false
    name: ${{ matrix.config.name }} File Upload Test [${{ matrix.runs-on }}]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Upload
      uses: ./
      with:
        name: ${{ matrix.config.name }}-${{ matrix.runs-on }}
        path: ${{ matrix.config.path }}
        retention-days: 1
    - name: Download Archive
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.config.name }}-${{ matrix.runs-on }}
        path: check
    - name: Check Archive Exists
      run: |
        count=$(ls -1 *.rTmpArchive.zip 2>/dev/null | wc -l)
        if [ $count != 1 ]; then
          echo "Missing archive file!"
          exit 1
        fi
      working-directory: check
    - name: Check Archive contents
      run: |
        unzip *.rTmpArchive.zip -d check/tmp

        EXPANDED_PATHS="${{ matrix.config.expanded_paths }}"
        
        PATH_COUNT=0
        echo "$EXPANDED_PATHS" | while IFS= read -r PATH
        do
          FULL_PATH=check/tmp/$PATH
          echo "Checking if file exists: $FULL_PATH"
          if [ ! -f "$FULL_PATH" ]; then
            echo "Missing file in archive: $FULL_PATH"
            exit 1
          fi
          ((PATH_COUNT++))
        done
        echo "Done checking files."

        unzipped_file_count=$(find check/tmp -type f | wc -l)
        if [ ! "$unzipped_file_count" -eq "$PATH_COUNT" ]; then
          echo "Encountered more files than expected; expected: [$PATH_COUNT], actual: [$unzipped_file_count]";
        fi